### ISSUE TITLE
OverlayFS error -38 in repo subdirectories on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by dmwarren** [cvmfs/cvmfs#3005] opened 2022-07-20 19:06 UTC
# Description
With cvmfs-server-2.9.4~1+ubuntu22.04, creating additional objects beneath `/cvmfs/${newly_created_repo}/${any_given_subdirectory}` results in this error:

`overlayfs: failed to retrieve lower fileattr (/foodir, err=-38)`

# Steps to reproduce the issue
1. Install Ubuntu 22.04 LTS.

2. Install cvmfs-server-2.9.4~1+ubuntu22.04.

3. `cvmfs_server mkfs testrepo.example.com` -- use defaults

4. `cvmfs_server transaction testrepo.example.com`

5. `mkdir /cvmfs/testrepo.example.com/foodir`

6. `cvmfs_server publish testrepo.example.com`

7. `cvmfs_server transaction testrepo.example.com`

8. `touch /cvmfs/testrepo.example.com/foodir/foofile`

9. Observe error message:
`touch: cannot touch '/cvmfs/testrepo.example.com/foodir/foofile': Function not implemented`

10. Observe syslogged error:
`Jul 20 17:28:28 u22publisher kernel: overlayfs: failed to retrieve lower fileattr (/foodir, err=-38)`

# Expected Result
You should be able to create files and directories freely in `/cvmfs/testrepo.example.com/${subdirectory}`.

# Actual Result
See error messages in steps 9 and 10 above. 
No files or directories are created.

# Additional Details
We discovered this when trying to use Ubuntu 22.04 as a publisher. This feels more like a bug in overlayfs but I'm logging it because CVMFS' Ubuntu 22.04 support probably hasn't had much testing yet. 

Our test host:
```
$ uname -a
Linux u22publisher 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ mount | grep lv   # root filesystem is ext4
/dev/mapper/ubuntu--vg-ubuntu--lv on / type ext4 (rw,relatime)

$ dpkg --list | grep fuse
cvmfs-fuse3        2.9.4~1+ubuntu22.04
fuse3              3.10.5-1build1     
libfuse2:amd64     2.9.9-5ubuntu3     
libfuse3-3:amd64   3.10.5-1build1     
```

An additional warning is syslogged when mounting any CVMFS repository:
`overlayfs: null uuid detected in lower fs '/', falling back to xino=off,index=off,nfs_export=off.`

**Comment by jblomer** [comment] 2022-07-21 09:19
I haven't yet looked into it but my first guess is that it's our use of overlayfs mount options.  We may be missing something for using fuse as a lower layer.

**Comment by DrDaveD** [comment] 2022-07-21 13:54
A perhaps related observation: I now have the apptainer main branch using unprivileged overlayfs when it works and otherwise fuse-overlayfs, and I found this week that on Rocky8 overlayfs works when the upper layer was a directory on a regular ext3 host filesystem, but it gave an "invalid argument" error when the upper layer was a fuse2fs-mounted ext3 filesystem.  In both cases the lower layer was squashfuse.  I hadn't thought to check syslog but I tried again and found a bunch of messages there:
```
Jul 21 08:57:41 localhost kernel: overlayfs: upper fs needs to support d_type.
Jul 21 08:57:41 localhost kernel: overlayfs: upper fs does not support tmpfile.
Jul 21 08:57:41 localhost kernel: overlayfs: upper fs does not support RENAME_WHITEOUT.
Jul 21 08:57:41 localhost kernel: overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.
Jul 21 08:57:41 localhost kernel: overlayfs: upper fs missing required features.
```
so it's probably a different problem.

**Comment by aebruno** [comment] 2022-08-04 14:03
Just wanted to add to this. We're also seeing the exact same issues on Ubuntu 20.04 since upgrading to the latest `cvmfs-server-2.9.4~1+ubuntu20.04`. This was working with the previous `2.9.2~1+ubuntu20.04 release`. 

```
$ cvmfs_server transaction our.test.repo.edu
$ touch: cannot touch '/cvmfs/our.test.repo.edu/versions/easybuild/software/.cvmfscatalog': Function not implemented
```
Observe syslogged error:

```
Aug  4 13:57:50 srv-p22-34 kernel: [781967.747299] overlayfs: failed to retrieve lower fileattr (/versions, err=-38)
```

**Comment by jblomer** [comment] 2022-08-08 20:27
It's hard to imagine what could have changed in cvmfs between the two versions that could cause the issue.  Is it possible that the Linux kernel was updated at the same time?

**Comment by aebruno** [comment] 2022-08-08 23:54
> It's hard to imagine what could have changed in cvmfs between the two versions that could cause the issue. Is it possible that the Linux kernel was updated at the same time?

@jblomer Thanks for the reply. Yes, linux kernel was updated at the same time from `linux-image-5.13.0-37` to `linux-image-5.15.0-41-generic`. We run ubuntu HWE kernels which explains the jump from 5.13 to 5.15. Let me know if there's any other info we can provide to help debug this.

**Comment by dmwarren** [comment] 2022-08-09 00:22
This OverlayFS-related change generates the same error for others. I have no idea if it's directly related.

https://lore.kernel.org/lkml/4B9D76D5-C794-4A49-A76F-3D4C10385EE0@kohlschutter.com/

**Comment by aebruno** [comment] 2022-08-09 03:38
@jblomer @dmwarren Thanks for the pointers. I can confirm rolling back to the latest Ubuntu 20.04 LTS  `5.4.0-122-generic` kernel fixed the issue. So it does appear to be a kernel related issue.

**Comment by jblomer** [comment] 2022-08-31 13:11
Same for Ubuntu 22.04: with a newer mainline kernel the issue disappears.

**Comment by jblomer** [comment] 2023-01-27 10:10
Closing, please feel free to reopen if necessary

**Closed as completed by jblomer** 2023-01-27 10:10 UTC
Labels: question, ::Server
