### ISSUE TITLE
Locked DB error during concurrent publish via CVMFS gateway

### ISSUE THREAD

**Issue by nicolamori** [cvmfs/cvmfs#3077] opened 2022-10-09 07:35 UTC
When doing simultaneous transactions on different paths of the same repository with two CVMFS publishers I sometimes get errors like this:
```
Using auto tag 'generic-2022-10-07T14:14:04Z'
Warning: CAP_DAC_READ_SEARCH cannot be obtained. It's not in the process's permitted set.
Processing changes...
Waiting for upload of files before committing...
Committing file catalogs...
Wait for all uploads to finish
Exporting repository manifest
Lease end request - error reply: {"reason":"could not commit transaction: database is locked","status":"error"}
SessionContext: could not commit session. Aborting.
[ERROR] Failed to commit transaction.
Statistics stored at: /var/spool/cvmfs/herd.sw.common/stats.db
Synchronization failed
Executed Command:
cvmfs_swissknife sync -u /cvmfs/herd.sw.common -s /var/spool/cvmfs/herd.sw.common/scratch/current -c /var/spool/cvmfs/herd.sw.common/rdonly -t /var/spool/cvmfs/herd.sw.common/tmp -b c6c80f5c7300b50c3b4545658e702d0a7d9e732c -r gw,/srv/cvmfs/herd.sw.common/data/txn,http://gateway.131.154.96.113.myip.cloud.infn.it/api/v1 -w https://minio-herd.cloud.cnaf.infn.it/cvmfs/herd.sw.common -o /var/spool/cvmfs/herd.sw.common/tmp/manifest -e sha1 -Z default -C /etc/cvmfs/repositories.d/herd.sw.common/trusted_certs -N herd.sw.common -K /etc/cvmfs/keys/herd.sw.common.pub -L -D generic-2022-10-07T14:14:04Z -G 00 -H /etc/cvmfs/keys/herd.sw.common.gw -P /var/spool/cvmfs/herd.sw.common/session_token -f overlayfs -p -l 4194304 -a 8388608 -h 16777216 -i
```
I guess this is due to trying to publish the two transactions at the same time. See also the [forum discussion](https://cernvm-forum.cern.ch/t/avoid-conflicts-when-publishing-from-different-publishers/233).

**Comment by jblomer** [comment] 2023-07-14 08:15
Duplicate of #3259, fixed by #3258

**Closed as completed by jblomer** 2023-07-14 08:15 UTC
Labels: bug, duplicate, ::Gateway
