### ISSUE TITLE
Incompatibility with kernel 6.1.11

### ISSUE THREAD

**Issue by teobouvard** [cvmfs/cvmfs#3199] opened 2023-02-15 14:55 UTC
Hello,

The CVMFS client 2.10 is not compatible with kernel 6.1.11. All `cvmfs_*` commands hang. Running them using `strace` shows `close()` calls on eternally-incremented file descriptors, which seems strange.

```bash
$ sudo strace -ff cvmfs_config bugreport
```
[strace output](https://gist.github.com/teobouvard/2fb973a5d103241c2b046b4071443138)

OS info:

```bash
$ uname -a
Linux HoG 6.1.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 09 Feb 2023 20:06:08 +0000 x86_64 GNU/Linux
```

I can provide additional info if you need.

**Comment by mohammad-akhlaghi** [comment] 2023-02-15 15:29
I can confirm that the same happened on my operating system after updating the Linux kernel to 6.1.11.

What ever change is causing this in the Linux kernel will propagate to other operating systems in the coming months, so I hope it can be fixed as soon as possible here. I can also share any additional info on my running environment if necessary.

**Comment by jblomer** [comment] 2023-02-15 15:36
It looks like a duplicate of #3158 
If the 6.11 kernel bumped the open file descriptor limit to insanely high, than we may need to backport the fix to the 2.10.1 release.

**Comment by jblomer** [comment] 2023-02-15 15:41
Just tried on a 6.1.11 kernel on arch Linux. I cannot reproduce the problem there.  Which OS are you using?

**Comment by mohammad-akhlaghi** [comment] 2023-02-15 15:43
I am also using Arch, but the CVMFS is loaded within a CentOS docker container. I am sure @teobouvard can give a more complete description.

**Comment by teobouvard** [comment] 2023-02-15 15:52
Also using Arch, and I experience the same issue as @mohammad-akhlaghi because we run CVMFS inside a Docker container, which does not use the limits of the host by default.

On the host:
```bash
$ ulimit -n
1024
```

In the container:
```bash
$ ulimit -n
1073741816
```

The root cause of the issue is #3158, thanks for the quick answer. Feel free to close this issue as the fix seems to be tracked on your 2.11 milestone.

For future reference, Docker users can workaround this issue by setting a lower `ulimit` on container startup.

```bash
docker run --ulimit nofile=4096:4096 ...
```

**Comment by mohammad-akhlaghi** [comment] 2023-02-15 18:14
Thanks a lot @jblomer and @teobouvard, setting the ulimit at the start of docker fixed the problem for me also.

**Comment by HereThereBeDragons** [comment] 2023-02-20 16:27
Closing as a fix was found

**Closed as completed by HereThereBeDragons** 2023-02-20 16:27 UTC
Labels: question
