### ISSUE TITLE
CVMFS Instability on Interactive Nodes

### ISSUE THREAD

**Issue by tomeichlersmith** [cvmfs/cvmfs#3151] opened 2023-01-09 14:36 UTC
My name is Tom and I am a graduate student at the University of Minnesota where we have a cluster using CVMFS to support our CMS group with their work. We are observing some instability with CVMFS in some of our nodes, specifically every few weeks CVMFS is "dropped" on our interactive nodes (more details of the symptoms below). We have developed a crude procedure for getting CVMFS back online (we wipe the cache with `cvmfs_config wipecache` and then restart autofs with `service autofs restart`), but I am curious if there is an improvement to our configuration so that this doesn't happen as frequently.

I have dumped a lot of information below in order to help inform you of our setup.

## Cluster
The affected systems are four interactive nodes. They are running the same OS as the non-interactive nodes (Rocky 8.6) and (to my knowledge) have the same Puppet configuration as each other except for the HTCondor configuration labeling them as either SUBMIT or EXECUTE nodes. What is particularly frustrating is that our non-interactive (aka worker) nodes don't seem to have this dropping problem - whenever condor jobs are executed on them, CVMFS has always been available. The worker nodes consist of machines that are older and newer than the interactive nodes, so I've been assuming it is not a hardware issue. We have another interactive node that has the same configuration (to my knowledge) as the four that are affected but does not experience this issue.

**Caveat**: We are a relatively small research group so our cluster is not always running jobs. Theoretically, CVMFS could drop from a worker node and then come back on its own and we wouldn't notice. I am assuming this is not the case since we have never seen CVMFS "come back" on its own on one of the interactive nodes.

## Symptoms
CVMFS "drops" and in the `/cvmfs/` directory we can only see `cvmfs-config.cern.ch` listed. Attempting to retrieve `cms.cern.ch` by `ls /cvmfs/cms.cern.ch` produces a "does not exist" error. 

## CVMFS chksetup
All nodes in our cluster produce the same output when I run `cvmfs_config chksetup`:
```
Warning: CernVM-FS drop-in map /etc/auto.master.d/cvmfs.autofs is not referenced from autofs master map /etc/auto.master
Warning: failed to access http://cvmfs-stratum-one.cern.ch:8000/cvmfs/atlas.cern.ch/.cvmfspublished through proxy http://cse-app-squid-01.cse.umn.edu:3128
Warning: failed to access http://cvmfs-stratum-one.cern.ch:8000/cvmfs/atlas.cern.ch/.cvmfspublished through proxy http://cse-app-squid-02.cse.umn.edu:3128
Warning: failed to access http://cernvmfs.gridpp.rl.ac.uk:8000/cvmfs/atlas.cern.ch/.cvmfspublished through proxy http://cse-app-squid-01.cse.umn.edu:3128                                                         
Warning: failed to access http://cvmfsrep.grid.sinica.edu.tw:8000/cvmfs/atlas.cern.ch/.cvmfspublished through proxy http://cse-app-squid-01.cse.umn.edu:3128                                                      
Warning: failed to use Geo-API with cvmfsrep.grid.sinica.edu.tw
Warning: failed to access http://cvmfsrep.grid.sinica.edu.tw:8000/cvmfs/atlas.cern.ch/.cvmfspublished through proxy http://cse-app-squid-02.cse.umn.edu:3128                                                      
Error: no public keys in /etc/cvmfs/keys
Error: required parameter CVMFS_SERVER_URL undefined for cms.hep.wisc.edu
Warning: failed to access http://cvmfs-egi.gridpp.rl.ac.uk:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-01.cse.umn.edu:3128                                 
Warning: failed to access http://cvmfs-egi.gridpp.rl.ac.uk:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-02.cse.umn.edu:3128                                 
Warning: failed to access http://klei.nikhef.nl:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-01.cse.umn.edu:3128                                            
Warning: failed to access http://klei.nikhef.nl:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-02.cse.umn.edu:3128                                            
Warning: failed to access http://cvmfsrep.grid.sinica.edu.tw:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-01.cse.umn.edu:3128                               
Warning: failed to access http://cvmfsrep.grid.sinica.edu.tw:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-02.cse.umn.edu:3128                               
Warning: failed to access http://cvmfs-stratum-one.ihep.ac.cn:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-01.cse.umn.edu:3128                              
Warning: failed to access http://cvmfs-stratum-one.ihep.ac.cn:8000/cvmfs/mu2e-development.opensciencegrid.org/.cvmfspublished through proxy http://cse-app-squid-02.cse.umn.edu:3128
```

## Debug Logging
We did think of generating a debug log of CVMFS on one of the affected machines. Unfortunately, CVMFS was up for about a week until it was dropped so the log is rather large (2.2GB uncompressed); a link to download the compressed version is below. I have not been able to find an obvious culprit in the log. It ends when we wiped the cache and restarted autofs. I also have attached the output of `cvmfs_config showconfig cms.cern.ch` for further information.

[CVMFS Debug Log Download (via Google Drive)](https://drive.google.com/file/d/1PqtDF6UAe5RuyMSQv7VqxU9-Hu3_yM-E/view?usp=sharing)
[showconfig_cms.cern.ch.log](https://github.com/cvmfs/cvmfs/files/10373983/showconfig_cms.cern.ch.log)

**Comment by tomeichlersmith** [comment] 2023-01-09 14:48
(If I should move this to the CVMFS Forum, I can just let me know.)

**Comment by jblomer** [comment] 2023-01-10 21:26
This may have been better for the forum but no need to switch now, let's handle it here.

**Comment by jblomer** [comment] 2023-01-10 21:45
The problem is related to namespaces / container runtimes. The hint is this line in the debug log (should also appear in the system log): "Transfer fuse connection to new mount".  The full details are in [CVM-2004](https://sft.its.cern.ch/jira/browse/CVM-2004).  Up until recent EL9 kernels, a container runtime (or anything using user namespaces) can take a cvmfs mountpoint with it into a private namespace. The system will after a while of idle time unmount the repository through autofs but it cannot remount because the private namespace blocks it.

Besides upgrading the OS, you can also take autofs out of the loop and [mount statically through /etc/fstab](https://cvmfs.readthedocs.io/en/stable/cpt-configure.html#mounting) on the interactive nodes (provided you only need a few cvmfs repositories). Alternatively, you can set a very long timeout in the autofs configuration. Recent versions of apptainer avoid this problem by marking the cvmfs mountpoint as busy while the container is running (but it may be difficult to control the container runtimes on the cluster).

**Comment by DrDaveD** [comment] 2023-01-11 18:06
Usually the problem is caused by a process escaping from singularity or apptainer and continuing to run in the background.  It's only a very old version of singularity that could cause it on its own.  Starting in recent EL9 kernels, cvmfs can reconnect to the background cvmfs2 process and re-use the mount.  Meanwhile the mitigation is to use `cvmfs_config fuser <reponame>` to find out which processes are still holding an old mount and preventing it from remounting.

**Comment by jblomer** [comment] 2023-01-17 09:20
Closing, please feel free to reopen if needed.

**Closed as completed by jblomer** 2023-01-17 09:20 UTC
Labels: question, ::Client
