### ISSUE TITLE
Allow aborting a transaction when session token is missing

### ISSUE THREAD

**Issue by aandvalenzuela** [cvmfs/cvmfs#3159] opened 2023-01-18 16:10 UTC
Hello,

Aborting a transaction fails when the session token is missing with:
```
[16:40][cvcmsibtest@lxcvmfs178 (ffurano_cvmfs_arm:cvmfs/lx)cms-ib-test.cern.ch]$ cvmfs_server abort cms-ib-test.cern.ch
You are about to DISCARD ALL CHANGES OF THE CURRENT TRANSACTION for cms-ib-test.cern.ch!  Are you sure (y/N)? y
HTTP Uploader - Could not open session token file. Aborting.
cvmfs_publish: /Users/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-aarch64/CVMFS_BUILD_PLATFORM/cc8/build/BUILD/cvmfs-2.10.0/cvmfs/upload_facility.h:138: virtual upload::AbstractUploader::~AbstractUploader(): Assertion `!tasks_upload_.is_active()' failed.
/usr/bin/cvmfs_server: line 4023: 2096637 Aborted                 $(__publish_cmd dbg) abort $@
```
I am not sure how the session token was deleted, but:
```
[16:40][cvcmsibtest@lxcvmfs178 (ffurano_cvmfs_arm:cvmfs/lx)cms-ib-test.cern.ch]$ ls /var/spool/cvmfs/cms-ib-test.cern.ch/
cache  client.local  cvmfs_io  data  in_transaction.lock  ofs_workdir  ovl_work  rdonly  scratch  tmp
```
After discussing with @HereThereBeDragons, could it be possible to avoid having the assertion in the `AbstractUploader` destructor (https://github.com/cvmfs/cvmfs/blob/devel/cvmfs/upload_facility.h#L138) and abort the current transaction nicely?

Thanks! :)

FYI, @smuzaffar

**Comment by jblomer** [comment] 2023-01-18 16:37
I think this is a duplicate of #3088
As of the upcoming 2.10.1 patch release, `cvmfs_server abort -f` should work without a session token file (abort without the `-f` will still complain though).

**Comment by HereThereBeDragons** [comment] 2023-01-19 14:10
im not sure if this solves all the issues. need to be testet as here it is about a missing `session_token` and not an `invalid lease`

looking in the PR this `if` might need rework? https://github.com/cvmfs/cvmfs/blob/38fd9135c0a654e83317ab450979ccb43593903f/cvmfs/publish/repository_abort.cc#L25-L28

and not sure about this line `unlink(session->token_path().c_str());` if this breaks if the file/path does not exist anymore

**Comment by jblomer** [comment] 2023-01-19 14:12
Good point! I'll take a look.

**Comment by HereThereBeDragons** [comment] 2023-01-25 16:25
Related #2844

**Closed as completed** 2023-02-13 09:41 UTC
Labels: ::Server, ::Gateway
