### ISSUE TITLE
Automatic garbage collection fails when coinciding with publication

### ISSUE THREAD

**Issue by deesto** [cvmfs/cvmfs#2968] opened 2022-05-09 20:27 UTC
GC runs weekly on a Stratum Zero via cron (via `gc -af`). Auto-GC is enabled:
```
# grep -r GC /etc/cvmfs/|grep -v keys
/etc/cvmfs/repositories.d/(repo)/server.conf:CVMFS_AUTO_GC=true
# grep -r GARBAGE /etc/cvmfs/|grep true
/etc/cvmfs/repositories.d(repo)/server.conf:CVMFS_GARBAGE_COLLECTION=true
```
(are both parameters necessary for a Stratum Zero, or redundant?)

GC runs often simultaneously with the publication of a busy repository, in which case it fails to run, with the following logged:

```
Starting (repo) at Sat May  7 03:13:35 EDT 2022
Cannot run garbage collection while in a transaction
ERROR from cvmfs_server gc!
Finished (repo) at Sat May  7 03:13:35 EDT 2022 
```

```
# uname -a
Linux cvmfs-s0a.sdcc.bnl.gov 3.10.0-1127.13.1.el7.x86_64 #1 SMP Fri Jun 12 14:34:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
# rpm -qa --last|grep cvmfs
cvmfs-2.9.2-1.el7.x86_64                      Thu 31 Mar 2022 09:30:54 AM EDT
cvmfs-server-2.9.2-1.el7.x86_64               Thu 31 Mar 2022 09:30:51 AM EDT
cvmfs-config-default-2.0-1.noarch             Fri 09 Oct 2020 05:07:14 PM EDT
cvmfs-release-2-6.noarch                      Thu 30 Mar 2017 11:47:15 AM EDT
```

**Comment by DrDaveD** [comment] 2022-05-09 21:17
This is a follow-on of [CVM-1921](https://sft.its.cern.ch/jira/browse/CVM-1921).

Are you sure that the auto gc isn't running?  It would show up at seemingly random times in the snapshot log.  There would be messages "Running automatic garbage collection" and if it succeeds, the last_gc time would be updated in `/srv/cvmfs/(repo)/.cvmfs_status.json`.

CVMFS_GARBAGE_COLLECTION and CVMFS_AUTO_GC options are not redundant.  The former means that the repository is collectable, and the latter says to run it automatically after publish operations on the stratum 0.  It's true that if only the latter were set it could infer the former, but that's not the way it has been set up to work.

A cron-based weekly gc is expected to fail if a publish transaction is running.   Perhaps there should be an option to the gc command to have it wait until a transaction is finished and run then.  Also, as discussed in today's developer meeting, perhaps there should be an option to the transaction command to abort a gc in progress.

**Comment by DrDaveD** [comment] 2022-05-09 21:22
> seemingly random times in the snapshot log

I'm sorry, I was thinking stratum 1 and you're talking about stratum 0.  It would show up in the publish log, which perhaps you don't see.  There would be messages in /var/log/messages, and `.cvmfs_status.json` should still be updated as I described.

**Comment by deesto** [comment] 2022-05-10 13:57
Then perhaps I'm conflating cron attempt failures, which are logged to `gc.log`, and auto attempts, which don't seem to be logged at all by default? I see there is a `CVMFS_GC_DELETION_LOG`, which is not set by default, but seems to be a valid parameter at both the server and repository levels. Does this collect the same information at both levels?

Thanks for the `JSON` tips. I do see only a last GC datestamp in these files. Should this contain more information than just a date (or, could it?)? It seems the only way to see what's happening is to dig into the sqlite files (in ` /var/spool/cvmfs/(repo)/stats.db`).

I definitely agree with:
>  Perhaps there should be an option to the gc command to have it wait until a transaction is finished and run then. Also, as discussed in today's developer meeting, perhaps there should be an option to the transaction command to abort a gc in progress.

**Comment by DrDaveD** [comment] 2022-05-10 14:41
.cvmfs_status.json only contains a date.  What is the date, is it recent?

Auto gc is considered to be part of the publish step so it goes to the publish log seen by the user.  There should also be some rough details about starts & stops and failures in /var/log/messages.

**Comment by deesto** [comment] 2022-05-10 16:00
Yes, the date in the JSON files is recent. But I can see from the sqlite DB that the auto run date seems to be splayed between 16-24 hours, which will often conflict with normal operating hours. Is there any way to control permissible run times with mor precision than "every once in a while" or via `CVMFS_AUTO_GC_LAPSE` (default 1 day)?

The only messages sent to syslog are complaints about other parameters not being set, e.g.,
`cvmfs_swissknife: Parameter CVMFS_EXTENDED_GC_STATS was not set in the repository configuration file. condemned_bytes were not counted.`
Since this parameter is disabled by default (according to the documentation "due to the non-negligible computation cost"), I'm not sure why this is among the only output recorded.

**Comment by DrDaveD** [comment] 2022-05-10 16:55
Oh good, then the original request in this issue is satisfied and we should be able to close it soon.

There is not a way to control the auto gc timing with more precision.  The expectation has been that people who want to control the timing will not use auto gc.  Since it is always tied to a publish command, the auto gc timing is almost always going to be inconvenient.  A cron with timing controlled by the end user usually makes the most sense, with auto gc disabled.  In this case since the users complained about 2am your time I expect they're in Europe, so maybe late evening U.S. time would work for them, ask them.  Also, note that the cvmfs_server gc -a command was designed with stratum1 in mind, and I don't know of anybody else using it on a stratum0.  A separate cron per gc-able repo might work better.

The gc code is sending messages to syslog, as is the publish code.  Maybe there's something about your syslog configuration that is redirecting or hiding them.

> I definitely agree with:

> >  Perhaps there should be an option to the gc command to have it wait until a transaction is finished and run then. Also, as discussed in today's developer meeting, perhaps there should be an option to the transaction command to abort a gc in progress.

This should be a separate issue or perhaps 2.  However, I looked at the code for gc waiting.  On stratum1s, the gc code does already wait for a snapshot to finish (and snapshots are typically set to abort and try again later).  For stratum0s there isn't currently a function to wait for a transaction to finish.  I think it may be able to be added, but transactions are trickier because they're not tied to a running process.  If a machine crashes, it's not possible to tell from the `in_transaction` file whether or not it really is still in progress.  For that reason, the automated publishing scripts I have written always have their own locks that are tied to a process, and when they start again they can tell whether or not it's ok to forcibly remove the lock and to abort any transaction in progress (because the process associated with the lock is still there or dead).  There's not really enough information at the cvmfs_server level as it is designed to tell whether or not it's OK to wait for a transaction.

**Comment by deesto** [comment] 2022-05-10 18:16
> A cron with timing controlled by the end user usually makes the most sense, with auto gc disabled. 

That would be fine, but in my case, auto is the one succeeding, while cron runs fail (consistently).

**Comment by DrDaveD** [comment] 2022-05-10 18:25
Ask the users if there's a time that won't interfere with their tasks, or ask them to put it into their own scripts.  Presumably they are doing their own regular cleanup, and it probably makes most sense to run the gc right after they do the deletes.

**Comment by DrDaveD** [comment] 2023-03-13 21:20
@deesto This issue has been stagnant for a long time, can we close it?

**Comment by vvolkl** [comment] 2023-04-04 14:01
Closing for now, feel free to reopen if needed.

**Closed as completed by vvolkl** 2023-04-04 14:01 UTC
Labels: ::Server
